spring.application.name=Dzhailauva_Dinara
spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=postgres
spring.datasource.password=aranid05
spring.jpa.hibernate.ddl-auto=update